const data = {
  products: [
    {
      _id: "1",
      name: "Vintage Slick Shirt",
      category: "shirts",
      image: "/images/p1.png",
      price: 120,
      brand: "Innjeez",
      rating: 4.5,
      numReviews: 10,
      description: "High qaulity Innjeez vintage complete sets",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "shirts",
      image: "/images/p1.png",
      price: 100,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "High qaulity products",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "shirts",
      image: "/images/p1.png",
      price: 200,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "High qaulity products",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p1.png",
      price: 120,
      brand: "Nike",
      rating: 4.2,
      numReviews: 14,
      description: "High qaulity products",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/p1.png",
      price: 65,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "High qaulity products",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "shirts",
      image: "/images/p1.png",
      price: 120,
      brand: "Innjeez",
      rating: 4.5,
      numReviews: 10,
      description: "High qaulity products",
    },
  ],
};

export default data;
